# Generated by Django 5.2.7 on 2025-10-17 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='members.member'),
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='borrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='borrow.borrowrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='borrowitem',
            unique_together={('borrow', 'book')},
        ),
    ]
