# Generated by Django 5.2.7 on 2025-10-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='book',
        ),
    ]
